# Generated by Django 2.2.28 on 2026-08-19 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import libs.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('aiops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('base_url', models.CharField(max_length=500)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('key_id', models.CharField(default='primary', max_length=50)),
                ('api_key_data', models.TextField(blank=True, null=True)),
                ('json_mode', models.BooleanField(default=True)),
                ('request_timeout', models.PositiveIntegerField(default=30)),
                ('max_hosts', models.PositiveIntegerField(default=20)),
                ('knowledge_limit', models.PositiveIntegerField(default=8)),
                ('max_output_tokens', models.PositiveIntegerField(default=2000)),
                ('max_response_bytes', models.PositiveIntegerField(default=1048576)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_ai_provider_configs', to='account.User')),
            ],
            options={
                'db_table': 'ai_provider_config',
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
