# Generated by Django 2.2.28 on 2026-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0002_aiproviderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='api_format',
            field=models.CharField(
                choices=[
                    ('openai', 'OpenAI Chat Completions'),
                    ('anthropic', 'Anthropic Messages'),
                ],
                default='openai',
                max_length=16,
            ),
        ),
    ]
