# Generated by Codex for ops-platform M6 P5.

import uuid
from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('audit', '0002_remote_session_results'),
        ('incident', '0001_initial'),
        ('aiops', '0003_aiproviderconfig_api_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRemediationProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('proposed_action', models.CharField(max_length=64)),
                ('target_refs', models.TextField(default='[]')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险'), ('critical', '严重风险')], max_length=16)),
                ('validation_plan', models.TextField()),
                ('rollback_plan', models.TextField(blank=True, null=True)),
                ('citation_refs', models.TextField(default='[]')),
                ('status', models.CharField(choices=[('draft', '待提交'), ('approval_pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已取消'), ('expired', '已过期')], db_index=True, default='draft', max_length=16)),
                ('execution_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.now)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remediation_proposals', to='aiops.AIActionPlan')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_remediation_proposals', to='audit.ApprovalRequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_remediation_proposals', to='account.User')),
                ('incident_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_proposals', to='incident.IncidentRoom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'ai_remediation_proposals',
                'ordering': ('-updated_at', '-created_at'),
                'index_together': {('created_by', 'status'), ('action_plan', 'status'), ('incident_room', 'status')},
            },
        ),
    ]
