# Generated by Codex for ops-platform M6 P6.

import uuid
from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('audit', '0002_remote_session_results'),
        ('aiops', '0004_airemediationproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airemediationproposal',
            name='status',
            field=models.CharField(choices=[('draft', '待提交'), ('approval_pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已取消'), ('expired', '已过期'), ('executing', '执行登记中'), ('succeeded', '已验证成功'), ('failed', '验证失败'), ('rolled_back', '已回滚')], db_index=True, default='draft', max_length=16),
        ),
        migrations.CreateModel(
            name='AIRemediationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('manual_record', '人工执行记录'), ('platform_reference', '平台执行引用')], default='manual_record', max_length=32)),
                ('platform_action', models.CharField(blank=True, max_length=64, null=True)),
                ('execution_ref', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('execution_summary', models.TextField()),
                ('validation_result', models.TextField(blank=True, null=True)),
                ('rollback_result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', '执行登记中'), ('succeeded', '已验证成功'), ('failed', '验证失败'), ('rolled_back', '已回滚')], db_index=True, default='running', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True, default=datetime.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.now)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_remediation_executions', to='audit.ApprovalRequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_remediation_executions', to='account.User')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='aiops.AIRemediationProposal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'ai_remediation_executions',
                'ordering': ('-started_at', '-created_at'),
                'index_together': {('proposal', 'status'), ('created_by', 'status')},
            },
        ),
    ]
