# Generated by Codex for ops-platform M6 P7.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiops', '0005_airemediationexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='airemediationexecution',
            name='platform_record',
            field=models.TextField(default='{}'),
        ),
    ]
