# Generated by Django 2.2.28 on 2026-08-17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_filetransfer_cleanup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransferBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True, editable=False)),
                ('directory', models.CharField(max_length=1024)),
                ('file_count', models.PositiveSmallIntegerField()),
                ('total_size', models.BigIntegerField()),
                ('max_concurrency', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('active', '传输中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='active', max_length=16)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='file_transfer_batch', to='audit.ApprovalRequest')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_transfer_batches', to='account.User')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_transfer_batches', to='host.Host')),
            ],
            options={
                'db_table': 'file_transfer_batches',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='file.FileTransferBatch'),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filetransfer',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_transfers', to='audit.ApprovalRequest'),
        ),
        migrations.AddIndex(
            model_name='filetransferbatch',
            index=models.Index(fields=['creator', 'status'], name='file_batch_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='filetransfer',
            index=models.Index(fields=['batch', 'status'], name='file_batch_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filetransfer',
            unique_together={('batch', 'filename')},
        ),
    ]
