# Generated by Django 2.2.28 on 2026-08-17

from django.db import migrations, models
import django.db.models.deletion
import uuid

import apps.file.models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_filetransferbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEditSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True, editable=False)),
                ('remote_path', models.CharField(max_length=1280)),
                ('path_hash', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=255)),
                ('temporary_path', models.CharField(max_length=1280)),
                ('base_size', models.BigIntegerField()),
                ('base_mtime', models.BigIntegerField()),
                ('base_etag', models.CharField(max_length=66)),
                ('base_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', '编辑中'), ('saved', '已保存'), ('cancelled', '已取消'), ('expired', '已过期')], db_index=True, default='active', max_length=16)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.file.models.file_edit_expiry)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_status', models.CharField(choices=[('pending', '待清理'), ('removed', '已删除'), ('missing', '文件不存在'), ('failed', '清理失败')], db_index=True, default='pending', max_length=16)),
                ('cleanup_attempts', models.PositiveSmallIntegerField(default=0)),
                ('cleanup_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('cleanup_error', models.CharField(blank=True, max_length=255, null=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_edit_sessions', to='audit.ApprovalRequest')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_edit_sessions', to='account.User')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_edit_sessions', to='host.Host')),
            ],
            options={
                'db_table': 'file_edit_sessions',
                'ordering': ('-updated_at',),
                'unique_together': {('host', 'path_hash')},
            },
        ),
        migrations.AddIndex(
            model_name='fileeditsession',
            index=models.Index(fields=['editor', 'status'], name='file_edit_editor_status_idx'),
        ),
    ]
