# Generated by Django 2.2.28 on 2026-08-14 14:53

from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('ssh_key', 'SSH private key'), ('password', 'Password'), ('token', 'API token')], max_length=20)),
                ('key_id', models.CharField(default='primary', max_length=50)),
                ('secret_data', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'asset_credentials',
                'ordering': ('name',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('protocol', models.CharField(choices=[('ssh', 'SSH'), ('sftp', 'SFTP'), ('rdp', 'RDP'), ('vnc', 'VNC')], max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('privilege_mode', models.CharField(choices=[('none', 'None'), ('sudo', 'sudo'), ('su', 'su')], default='none', max_length=10)),
                ('constraints', models.TextField(default='{}')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='assets.Credential')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'asset_identities',
                'ordering': ('name',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='AssetIdentityBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_identity_bindings', to='host.Host')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_bindings', to='assets.Identity')),
            ],
            options={
                'db_table': 'asset_identity_bindings',
                'ordering': ('host_id', '-is_default', 'id'),
                'unique_together': {('host', 'identity')},
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=10)),
                ('actions', models.TextField(default='[]')),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('revoked_at', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='host.Group')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='host.Host')),
                ('identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='assets.Identity')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('subject_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_access_grants', to='account.Role')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_access_grants', to='account.User')),
            ],
            options={
                'db_table': 'asset_access_grants',
                'ordering': ('-id',),
                'index_together': {('subject_role', 'status'), ('host', 'status'), ('group', 'status'), ('subject_user', 'status')},
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
