# Generated by Django 2.2.28 on 2026-08-18

import datetime
import django.db.models.deletion
from django.db import migrations, models
import libs.mixins
import libs.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exporter_address', models.CharField(max_length=255)),
                ('exporter_port', models.PositiveIntegerField(default=9100)),
                ('scheme', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=8)),
                ('metrics_path', models.CharField(default='/metrics', max_length=255)),
                ('notify_grp', models.TextField(default='[]')),
                ('notify_mode', models.TextField(default='[]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric_target', to='host.Host')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={'db_table': 'metric_targets', 'ordering': ('host_id',)},
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('episode', models.PositiveIntegerField(default=1)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alert_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], db_index=True, default='warning', max_length=16)),
                ('status', models.CharField(choices=[('firing', '告警中'), ('resolved', '已恢复')], db_index=True, default='firing', max_length=16)),
                ('instance', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('labels', models.TextField(default='{}')),
                ('annotations', models.TextField(default='{}')),
                ('starts_at', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(default=datetime.datetime.now)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('silenced_until', models.DateTimeField(blank=True, null=True)),
                ('silence_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('alertmanager_silence_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_metric_alerts', to='account.User')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_alerts', to='host.Host')),
                ('silenced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='silenced_metric_alerts', to='account.User')),
            ],
            options={
                'db_table': 'metric_alert_events',
                'ordering': ('-last_seen_at', '-id'),
                'unique_together': {('fingerprint', 'episode')},
                'index_together': {('host', 'status'), ('status', 'severity')},
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='AlertTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('firing', '告警发生'), ('resolved', '故障恢复'), ('claimed', '已认领'), ('unclaimed', '取消认领'), ('silenced', '已静默'), ('unsilenced', '取消静默')], max_length=16)),
                ('details', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='observability.AlertEvent')),
            ],
            options={'db_table': 'metric_alert_transitions', 'ordering': ('created_at', 'id')},
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
