global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: spug-node
    honor_labels: false
    http_sd_configs:
      - url: http://spug/api/v1/observability/discovery/targets/
        refresh_interval: 30s
        authorization:
          type: Bearer
          credentials_file: /run/secrets/prometheus_discovery_token
