# Generated by Codex for ops-platform M6 P4.

import uuid
from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '警告'), ('critical', '严重')], db_index=True, default='warning', max_length=16)),
                ('status', models.CharField(choices=[('open', '处理中'), ('mitigated', '已缓解'), ('resolved', '已恢复'), ('closed', '已关闭')], db_index=True, default='open', max_length=16)),
                ('topology_node_ids', models.TextField(default='[]')),
                ('ai_investigation_ids', models.TextField(default='[]')),
                ('postmortem_draft', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_rooms', to='observability.AlertEvent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_incident_rooms', to='account.User')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_incident_rooms', to='account.User')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'incident_rooms',
                'ordering': ('-updated_at', '-created_at'),
                'index_together': {('status', 'severity'), ('owner', 'status')},
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('created', '创建事件'), ('note', '人工备注'), ('status', '状态变更'), ('owner', '负责人变更'), ('postmortem', '复盘草稿'), ('ai', 'AI 调查关联')], db_index=True, max_length=32)),
                ('message', models.TextField()),
                ('details', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_incident_timeline', to='account.User')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='incident.IncidentRoom')),
            ],
            options={
                'db_table': 'incident_timeline',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
