# Generated by Django 2.2.28 on 2026-08-17

import apps.file.models
from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('audit', '0001_initial'),
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(db_index=True, editable=False)),
                ('directory', models.CharField(max_length=1024)),
                ('filename', models.CharField(max_length=255)),
                ('remote_path', models.CharField(max_length=1280)),
                ('temporary_path', models.CharField(max_length=1280)),
                ('size', models.BigIntegerField()),
                ('offset', models.BigIntegerField(default=0)),
                ('chunk_size', models.PositiveIntegerField()),
                ('expected_sha256', models.CharField(max_length=64)),
                ('actual_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('conflict_strategy', models.CharField(choices=[('overwrite', '覆盖'), ('reject', '拒绝')], default='overwrite', max_length=16)),
                ('status', models.CharField(choices=[('active', '上传中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('expired', '已过期')], db_index=True, default='active', max_length=16)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=apps.file.models.file_transfer_expiry)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='file_transfer', to='audit.ApprovalRequest')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_transfers', to='host.Host')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_transfers', to='account.User')),
            ],
            options={
                'db_table': 'file_transfers',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.AddIndex(
            model_name='filetransfer',
            index=models.Index(fields=['uploader', 'status'], name='file_uploader_status_idx'),
        ),
    ]
