# Generated by Django 2.2.28 on 2026-08-17

from django.db import migrations, models


def mark_completed_transfers_clean(apps, schema_editor):
    FileTransfer = apps.get_model('file', 'FileTransfer')
    FileTransfer.objects.filter(status='completed').update(
        cleanup_status='removed',
        cleanup_completed_at=models.F('completed_at'),
    )


def reset_completed_transfer_cleanup(apps, schema_editor):
    FileTransfer = apps.get_model('file', 'FileTransfer')
    FileTransfer.objects.filter(status='completed').update(
        cleanup_status='pending',
        cleanup_completed_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='cleanup_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='cleanup_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='cleanup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='cleanup_error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filetransfer',
            name='cleanup_status',
            field=models.CharField(choices=[('pending', '待清理'), ('removed', '已删除'), ('missing', '文件不存在'), ('failed', '清理失败')], db_index=True, default='pending', max_length=16),
        ),
        migrations.RunPython(
            mark_completed_transfers_clean,
            reset_completed_transfer_cleanup,
        ),
    ]
