# Generated by Django 2.2.28 on 2026-08-14 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployrequest',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
