# Generated by Django 2.2.28 on 2026-08-14 17:44

import apps.audit.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import uuid


def create_audit_chain(apps, schema_editor):
    AuditChain = apps.get_model('audit', 'AuditChain')
    AuditChain.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChain',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_sequence', models.BigIntegerField(default=0)),
                ('last_hash', models.CharField(default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_chain',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.BigIntegerField(unique=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('actor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(choices=[('requested', '已申请'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已撤销'), ('denied', '已拒绝'), ('queued', '已入队'), ('started', '已开始'), ('succeeded', '成功'), ('failed', '失败')], db_index=True, max_length=16)),
                ('source_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('request_method', models.CharField(blank=True, max_length=12, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(default='{}')),
                ('previous_hash', models.CharField(default='', max_length=64)),
                ('event_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ('-sequence',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_ids', models.TextField(default='[]')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险'), ('critical', '严重风险')], max_length=16)),
                ('summary', models.CharField(max_length=255)),
                ('rollback_plan', models.TextField(blank=True, null=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已撤销'), ('consumed', '已使用'), ('expired', '已过期')], db_index=True, default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.audit.models.approval_request_expiry)),
                ('approved_until', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_ref', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to='account.User')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='account.User')),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ('-requested_at',),
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.RunPython(create_audit_chain, migrations.RunPython.noop),
    ]
