# Generated by Django 2.2.28 on 2026-08-14 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_execution_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approval_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
