"""
# Copyright: (c) OpenSpug Organization. https://github.com/openspug/spug
# Copyright: (c) <spug.dev@gmail.com>
# Released under the AGPL-3.0 License.

Django settings for spug project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import re
from django.core.exceptions import ImproperlyConfigured
from .env_settings import load_security_settings

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# Development-only defaults. Production values are enforced after loading
# the optional overrides module at the bottom of this file.
SECRET_KEY = 'development-only-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'apps.account',
    'apps.audit',
    'apps.assets',
    'apps.gateway',
    'apps.observability',
    'apps.knowledge',
    'apps.aiops',
    'apps.file',
    'apps.host',
    'apps.setting',
    'apps.exec',
    'apps.schedule',
    'apps.monitor',
    'apps.alarm',
    'apps.config',
    'apps.app',
    'apps.deploy',
    'apps.notify',
    'apps.repository',
    'apps.home',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'libs.middleware.AuthenticationMiddleware',
    'libs.middleware.HandleExceptionMiddleware',
]

ROOT_URLCONF = 'spug.urls'

WSGI_APPLICATION = 'spug.wsgi.application'
ASGI_APPLICATION = 'spug.routing.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
            "capacity": 1000,
            "expiry": 120,
        },
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': False,
    },
]

TOKEN_TTL = 8 * 3600
SCHEDULE_KEY = 'spug:schedule'
SCHEDULE_WORKER_KEY = 'spug:schedule:worker'
MONITOR_KEY = 'spug:monitor'
MONITOR_WORKER_KEY = 'spug:monitor:worker'
EXEC_WORKER_KEY = 'spug:exec:worker'
REQUEST_KEY = 'spug:request'
BUILD_KEY = 'spug:build'
REPOS_DIR = os.path.join(os.path.dirname(os.path.dirname(BASE_DIR)), 'repos')
BUILD_DIR = os.path.join(REPOS_DIR, 'build')
TRANSFER_DIR = os.path.join(BASE_DIR, 'storage', 'transfer')

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

AUTHENTICATION_EXCLUDES = (
    '/account/login/',
    '/setting/basic/',
    re.compile('/apis/.*'),
    re.compile(r'^/v1/gateway/sessions/[0-9a-f-]+/launch/$'),
    re.compile(r'^/v1/observability/discovery/targets/$'),
    re.compile(r'^/v1/observability/alertmanager/webhook/$'),
)

SPUG_VERSION = 'v3.4.0'
OPS_PLATFORM_VERSION = os.environ.get('OPS_PLATFORM_VERSION', '0.1.0-alpha.12')

# override default config
try:
    from spug.overrides import *
except ImportError:
    pass


try:
    _security = load_security_settings(
        default_secret=SECRET_KEY,
        default_debug=DEBUG,
        default_allowed_hosts=ALLOWED_HOSTS,
    )
except ValueError as exc:
    raise ImproperlyConfigured(str(exc))

SPUG_ENV = _security['environment']
SPUG_CREDENTIAL_MASTER_KEY = _security['credential_master_key']
SPUG_CREDENTIAL_MASTER_KEYS = _security['credential_master_keys']
SPUG_CREDENTIAL_PRIMARY_KEY_ID = _security['credential_primary_key_id']
SPUG_AUDIT_SIGNING_KEY = _security['audit_signing_key']
SPUG_REMOTE_GATEWAY_ENABLED = _security['remote_gateway_enabled']
SPUG_OBSERVABILITY_ENABLED = _security['observability_enabled']
SPUG_AIOPS_ENABLED = _security['aiops_enabled']
SPUG_AIOPS_API_KEY = _security['aiops_api_key']
SPUG_AIOPS_BASE_URL = _security['aiops_base_url']
SPUG_AIOPS_MODEL = _security['aiops_model']
SPUG_AIOPS_JSON_MODE = _security['aiops_json_mode']
SPUG_AIOPS_REQUEST_TIMEOUT = _security['aiops_request_timeout']
SPUG_AIOPS_MAX_HOSTS = _security['aiops_max_hosts']
SPUG_AIOPS_KNOWLEDGE_LIMIT = _security['aiops_knowledge_limit']
SPUG_AIOPS_MAX_OUTPUT_TOKENS = _security['aiops_max_output_tokens']
SPUG_AIOPS_RATE_LIMIT_PER_MINUTE = _security['aiops_rate_limit_per_minute']
SPUG_AIOPS_MAX_RESPONSE_BYTES = _security['aiops_max_response_bytes']
SPUG_GUACAMOLE_JSON_SECRET_KEY = _security['guacamole_json_secret_key']
SPUG_GUACAMOLE_PUBLIC_URL = _security['guacamole_public_url']
SPUG_REMOTE_TICKET_TTL = _security['remote_ticket_ttl']
SPUG_GUACAMOLE_AUTH_TTL = _security['guacamole_auth_ttl']
SPUG_PROMETHEUS_DISCOVERY_TOKEN = _security['prometheus_discovery_token']
SPUG_ALERTMANAGER_WEBHOOK_TOKEN = _security['alertmanager_webhook_token']
SPUG_PROMETHEUS_URL = _security['prometheus_url']
SPUG_ALERTMANAGER_URL = _security['alertmanager_url']
SPUG_OBSERVABILITY_REQUEST_TIMEOUT = _security['observability_request_timeout']
SPUG_ALERTMANAGER_MAX_BODY = _security['alertmanager_max_body']
SPUG_ALERT_RETENTION_DAYS = _security['alert_retention_days']
SECRET_KEY = _security['secret_key']
DEBUG = _security['debug']
ALLOWED_HOSTS = _security['allowed_hosts']
CSRF_TRUSTED_ORIGINS = _security['csrf_trusted_origins']
SESSION_COOKIE_SECURE = _security['secure_cookies']
CSRF_COOKIE_SECURE = _security['secure_cookies']
SECURE_SSL_REDIRECT = _security['ssl_redirect']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
