# Generated by Django 2.2.28 on 2026-08-14 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exechistory',
            name='approval_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='exechistory',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='transfer',
            name='approval_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
