# Generated by Django 2.2.28 on 2026-08-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='host.Host'),
        ),
    ]
