# Generated by Django 2.2.28 on 2026-08-18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import libs.mixins
import libs.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAccessEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('rdp', 'RDP'), ('vnc', 'VNC')], max_length=10)),
                ('port', models.PositiveIntegerField()),
                ('display_name', models.CharField(max_length=100)),
                ('settings', models.TextField(default='{}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('updated_at', models.CharField(default=libs.utils.human_datetime, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_access_endpoints', to='host.Host')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remote_access_endpoints', to='assets.Identity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'remote_access_endpoints',
                'ordering': ('host_id', 'protocol'),
                'unique_together': {('host', 'protocol')},
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='RemoteAccessSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol', models.CharField(choices=[('rdp', 'RDP'), ('vnc', 'VNC')], max_length=10)),
                ('ticket_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('launched', 'Launched'), ('closed', 'Closed'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='issued', max_length=16)),
                ('issued_at', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='gateway.RemoteAccessEndpoint')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='host.Host')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.Identity')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remote_access_sessions', to='account.User')),
            ],
            options={
                'db_table': 'remote_access_sessions',
                'ordering': ('-issued_at',),
                'index_together': {('requester', 'status'), ('host', 'status')},
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
    ]
