# Generated by ops-platform on 2026-09-03

import datetime
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[('host', '服务器'), ('application', '应用'), ('service', '服务'), ('port', '监听端口'), ('database', '数据库'), ('middleware', '中间件'), ('external', '外部接口'), ('monitor_target', '监控目标')], max_length=32)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(choices=[('manual', '人工维护'), ('host', '主机资产'), ('application', '应用'), ('service', '配置服务'), ('metric_target', '监控采集目标'), ('runtime', '运行态快照'), ('external', '外部系统')], default='manual', max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('healthy', '正常'), ('info', '提示'), ('warning', '警告'), ('critical', '严重'), ('offline', '离线'), ('disabled', '停用'), ('unknown', '未知')], db_index=True, default='unknown', max_length=16)),
                ('status_source', models.CharField(choices=[('manual', '人工维护'), ('alert', '告警事件'), ('metrics', '监控指标'), ('probe', '探测结果'), ('runtime', '运行态快照'), ('inherited', '拓扑继承'), ('unknown', '未知')], default='manual', max_length=16)),
                ('metadata', models.TextField(default='{}')),
                ('position', models.TextField(default='{}')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_topology_nodes', to='account.User')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'topology_nodes',
                'ordering': ('type', 'name', 'id'),
                'index_together': {('type', 'status'), ('source_type', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='TopologyEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deployed_on', '部署于'), ('listens_on', '监听'), ('calls', '调用'), ('depends_on', '依赖'), ('collects', '采集'), ('alerts_on', '告警关联'), ('release_affects', '发布关联')], max_length=32)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('healthy', '正常'), ('info', '提示'), ('warning', '警告'), ('critical', '严重'), ('offline', '离线'), ('disabled', '停用'), ('unknown', '未知')], db_index=True, default='unknown', max_length=16)),
                ('status_source', models.CharField(choices=[('manual', '人工维护'), ('alert', '告警事件'), ('metrics', '监控指标'), ('probe', '探测结果'), ('runtime', '运行态快照'), ('inherited', '拓扑继承'), ('unknown', '未知')], default='manual', max_length=16)),
                ('probed', models.BooleanField(default=False)),
                ('metadata', models.TextField(default='{}')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_topology_edges', to='account.User')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='topology.TopologyNode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='topology.TopologyNode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.User')),
            ],
            options={
                'db_table': 'topology_edges',
                'ordering': ('source_id', 'target_id', 'type'),
                'unique_together': {('source', 'target', 'type')},
                'index_together': {('type', 'status')},
            },
        ),
    ]
