# Generated by ops-platform on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topologynode',
            name='type',
            field=models.CharField(choices=[
                ('host', '服务器'),
                ('application', '应用'),
                ('service', '服务'),
                ('process', '进程'),
                ('port', '监听端口'),
                ('database', '数据库'),
                ('middleware', '中间件'),
                ('external', '外部接口'),
                ('monitor_target', '监控目标'),
            ], max_length=32),
        ),
    ]
